# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mc_version=1.20.1

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47.3.10,)
loader_version_range=[47,)

parchment_mappings_version=2023.09.03
parchment_minecraft_version=1.20.1

# Mod Properties
mod_version=1.8-FORGE-1.20.1

mod_id=wdutils
mod_name=wd's Utils
mod_license=MIT
mod_group_id=com.wdiscute
mod_authors=wdiscute
mod_description=A set of useful classes and systems for minecraft modders