modLoader="javafml" #mandatory

loaderVersion="[2,]" #mandatory

license="MIT"

issueTrackerURL="https://discord.gg/WsuFsGSegD" #optional

[[mods]] #mandatory
modId="wdutils"
version="1.8.1-FORGE-1.20.1"
displayName="wd's Utils"
mod_authors="wdiscute"
description='''A set of useful classes and systems for minecraft modders'''

#[[mixins]]
#config="starcatcher.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.wdutils]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47.3.10,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.wdutils]]
modId="minecraft"
mandatory=true #mandatory
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"