modLoader="javafml" #mandatory

loaderVersion="[2,]" #mandatory

license="MIT"

issueTrackerURL="https://discord.gg/WsuFsGSegD" #optional

[[mods]] #mandatory
modId="wdutils"
version="${mod_version}"
displayName="${mod_name}"
displayURL="http://curseforge.com/minecraft/mc-mods/wds-utils"
logoFile = "icon.png"
mod_authors="${mod_authors}" #optional
description='''A set of useful classes and systems for minecraft modders'''

# In neoforge.mods.toml:
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.wdutils]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="AFTER"
side="BOTH"

[[dependencies.wdutils]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"